src/Entity/Quack.php
<?php

namespace App\Entity;

use App\Repository\QuackRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\ArrayShape;

/**
 * @ORM\Entity(repositoryClass=QuackRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Quack
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\ManyToOne(targetEntity=Ducks::class, inversedBy="quacks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $duck;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="Quack", cascade={"persist"})
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity=Quack::class, inversedBy="children" )
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity=Quack::class, mappedBy="parent", cascade={"remove", "persist"})
     */
    private $children;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $deleted;

    /**
     * @ORM\Column(type="integer")
     */
    private $positive;

    /**
     * @ORM\Column(type="integer")
     */
    private $negative;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updated_at;

    public function __construct($duck)
    {
        $this->tags = new ArrayCollection();
        $this->created_at = new \DateTime('now');
        $this->duck = $duck;
        $this->children = new ArrayCollection();
        $this->deleted = 0;
        $this->positive = 0;
        $this->negative = 0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDuck(): ?Ducks
    {
        return $this->duck;
    }

    public function setDuck(?Ducks $duck): self
    {
        $this->duck = $duck;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
            $tag->addQuack($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->removeElement($tag)) {
            $tag->removeQuack($this);
        }

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getChildren(): Collection
    {
        return $this->children;
    }

    public function addChild(self $child): self
    {
        if (!$this->children->contains($child)) {
            $this->children[] = $child;
            $child->setParent($this);
        }

        return $this;
    }

    public function removeChild(self $child): self
    {
        if ($this->children->removeElement($child)) {
            // set the owning side to null (unless already changed)
            if ($child->getParent() === $this) {
                $child->setParent(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return $this->content;
    }

    public function getDeleted(): ?int
    {
        return $this->deleted;
    }

    public function setDeleted(int $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getPositive(): ?int
    {
        return $this->positive;
    }

    public function setPositive(int $positive): self
    {
        $this->positive = $positive;

        return $this;
    }

    public function getNegative(): ?int
    {
        return $this->negative;
    }

    public function setNegative(int $negative): self
    {
        $this->negative = $negative;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updated_at;
    }

    /**
     * @ORM\PostUpdate()
     * @return $this
     */
    public function setUpdatedAt(): self
    {
        $this->updated_at = new \DateTimeImmutable('now');

        return $this;
    }


}

src/Form/QuackType.php
<?php

namespace App\Form;

use App\Entity\Quack;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuackType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('content')
            ->add('tags')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Quack::class,
        ]);
    }
}

src/Controller/QuackController.php
<?php

namespace App\Controller;

use App\Entity\Quack;
use App\Form\QuackType;
use App\Form\SearchType;
use App\Repository\QuackRepository;
use Doctrine\ORM\Query\AST\Functions\CurrentTimestampFunction;
use http\Env;
use Knp\Bundle\MarkdownBundle\MarkdownParserInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function Symfony\Component\DependencyInjection\Loader\Configurator\env;

/**
 * @Route("/quack")
 */
class QuackController extends AbstractController
{
    /**
     * @Route("/", name="quack_index", methods={"GET", "POST"})
     */
    public function index(Request $request, QuackRepository $quackRepository, MarkdownParserInterface $markdownParser): Response
    {
        if ($request->isMethod('POST')) {
            $searchKey = $request->request->get('search')['search'];
            $results = $quackRepository->findByAuthor($searchKey);
            $quacks = $results;
         } else {
            $quacks = $quackRepository->findNotDeleted();
        }

        foreach ($quacks as $quack) {
            $quack->setContent($markdownParser->transformMarkdown($quack->getContent()));
        }

        return $this->render('quack/index.html.twig', [
            'quacks' => $quacks,
        ]);
    }

    /**
     * @Route("/new", name="quack_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $quack = new Quack($this->getUser());

        $form = $this->createForm(QuackType::class, $quack);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($quack);
            $entityManager->flush();

            return $this->redirectToRoute('quack_index');
        }

        return $this->render('quack/new.html.twig', [
            'quack' => $quack,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="quack_show", methods={"GET"})
     */
    public function show(Quack $quack, MarkdownParserInterface $markdownParser): Response
    {
        if ($quack->getDeleted() === 1) {
            return $this->render('quack/deleted.html.twig', []);
        }

        $parsedQuack = $markdownParser->transformMarkdown($quack->getContent());

        return $this->render('quack/show.html.twig', [
            'quack' => $quack,
            'parsedQuack' => $parsedQuack,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="quack_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Quack $quack): Response
    {
        $this->denyAccessUnlessGranted('edit', $quack);

        $form = $this->createForm(QuackType::class, $quack);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quack->setUpdatedAt();
            $this->getDoctrine()
                ->getManager()
                ->flush();
            return $this->redirectToRoute('quack_index');
        }

        return $this->render('quack/edit.html.twig', [
            'quack' => $quack,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="quack_delete", methods={"POST"})
     */
    public function delete(Request $request, Quack $quack): Response
    {
        $this->denyAccessUnlessGranted('delete', $quack);

        if ($this->isCsrfTokenValid(
            'delete'.$quack->getId(),
            $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $quack->setDeleted(1);
            $entityManager->flush();
        }
        return $this->redirectToRoute('quack_index');
    }

    /**
     * @Route("/comment/{id}", name="quack_comment", methods={"GET", "POST"})
     */
    public function newComment(Request $request, Quack $parent): Response {
        $quack = new Quack($this->getUser());
        $quack->setParent($parent);

        $form = $this->createForm(QuackType::class, $quack);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($quack);
            $entityManager->flush();
            return $this->redirectToRoute('quack_index');
        }

        return $this->render('quack/newComment.html.twig', [
            'quack' => $quack,
            'parent' => $parent,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Search method to create the search bar
     * @return Response render form
     */
    public function search(): Response
    {
        $form = $this->createForm(SearchType::class);
        return $this->render('quack/search.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/like/{id}", name="quack_like")
     */
    public function likeQuack(Request $request, Quack $quack, ParameterBagInterface $parameterBag) {
        // protect direct access
        if ($request->headers->get('referer') ===
            $parameterBag->get('app_server') &&
            $this->getUser())
        {
            $quack->setPositive($quack->getPositive() + 1);
            $this->getDoctrine()
                ->getManager()
                ->flush();
        }
        return $this->redirectToRoute('index');
    }

    /**
     * @Route("/dislike/{id}", name="quack_dislike")
     */
    public function dislikeQuack(Request $request, Quack $quack, ParameterBagInterface $parameterBag) {
        // protect direct access
        if ($request->headers->get('referer') ===
            $parameterBag->get('app_server') &&
            $this->getUser())
        {
            $quack->setNegative($quack->getNegative() + 1);
            $this->getDoctrine()
                ->getManager()
                ->flush();
        }
        return $this->redirectToRoute('index');
    }
}

templates/quack/_delete_form.html.twig
<form method="post" action="{{ path('quack_delete', {'id': quack.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quack.id) }}">
    <button class="btn">Delete</button>
</form>

templates/quack/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/quack/deleted.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Il y a un quack avec ce quack</h1>
    <p>Ce quack n'existe plus !</p>
    <a href="{{ path('index') }}">Retour aux quacks</a>
{% endblock %}

{% block title %}
    Quack
{% endblock %}

templates/quack/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Quack{% endblock %}

{% block body %}
    <h1>Edit Quack</h1>

    {{ include('quack/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('quack_index') }}">back to list</a>

    {{ include('quack/_delete_form.html.twig') }}
{% endblock %}

templates/quack/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quack index{% endblock %}

{% block body %}
    {% if app.user %}

    {% else %}
        <a href="{{ path('app_login') }}">Se connecter</a>
        <a href="{{ path('app_register') }}">S'enregistrer'</a>
    {% endif %}
    <h1>Quack index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Content</th>
                <th>Created_at</th>
                <th>actions</th>
                <th>author</th>
                <th>tags</th>
                <th>Commentaires</th>
                <th>Likes</th>
                <th>Dislikes</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
        {% for quack in quacks %}
            <tr>
                <td>{{ quack.id }}</td>
                <td>{{ quack.content|auto_link|markdown }}</td>
                <td>{{ quack.createdAt ? quack.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    {% if app.user %}
                      {% if quack.duck is same as (app.user) or (quack.parent and quack.parent.duck is same as (app.user))%}
                            <form method="post" action="{{ path('quack_delete', {'id': quack.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quack.id) }}">
                                <button class="btn">Delete</button>
                            </form>
                        {% endif %}
                    {% endif %}
                </td>
                <td> <a href="{{ path('show_duck', {id: quack.duck.id}) }}">{{ quack.duck.username }}</a></td>
                <td>
                    {% for tag in quack.tags  %}
                        {{ tag }}
                    {% endfor %}
                </td>
                <td>
                    <a href="{{ path('quack_comment', {id: quack.id}) }}">Ajouter un commentaire</a>
                </td>
                <td>
                    <p>likes {{ quack.positive }}</p>
                    <a href="{{ path('quack_like', {'id': quack.id }) }}">like</a>
                </td>
                <td>
                    <p>dislikes {{ quack.negative }}</p>
                    <a href="{{ path('quack_dislike', {'id': quack.id }) }}">dislike</a>
                </td>
                <td>
                    {% if quack.duck is same as (app.user)  %}
                        <a href="{{ path('quack_edit', {id: quack.id}) }}">Edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <a href="{{ path('quack_new') }}">Create new</a>
{% endblock %}

templates/quack/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Quack{% endblock %}

{% block body %}
    <h1>Create new Quack</h1>

    {{ include('quack/_form.html.twig') }}

    <a href="{{ path('quack_index') }}">back to list</a>
{% endblock %}

templates/quack/newComment.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau commentaire{% endblock %}

{% block body %}
    <h1>Commenter</h1>

    <div>
        <h2>Coincoin de {{ parent.duck.username }}</h2>
        <p>{{ parent.content|markdown }}</p>
        <p>le {{ parent.createdAt|date("d/m/Y") }}</p>
    </div>

    {{ include('quack/_form.html.twig') }}

    <a href="{{ path('quack_index') }}">back to list</a>
{% endblock %}

templates/quack/search.html.twig
{{ form_start(form) }}
    {{ form_row(form.search) }}
    {{ form_row(form.coin) }}
{{ form_end(form) }}

templates/quack/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quack{% endblock %}

{% block body %}
    <h1>Quack</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ quack.id }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ parsedQuack|auto_link|markdown }}</td>
            </tr>
            <tr>
                <th>Publié le</th>
                <td>{{ quack.createdAt ? quack.createdAt|date('d-m-Y H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <div>
        <h3>Commentaires</h3>
            {% for comment in quack.children %}
                <p>Auteur : {{ comment.duck }}</p>
                <p>{{ comment.content }}</p>
                <p>Le {{ comment.createdAt|date('d-m-Y H:i:s') }}</p>
                <p>Tags :</p>
                    {% for tag in comment.tags %}
                        <p>{{ tag }}</p>
                    {% endfor %}
            {% endfor %}
    </div>
    <a href="{{ path('index') }}">Retour aux quacks</a>

{#    <a href="{{ path('quack_edit', {'id': quack.id}) }}">edit</a>#}

{#    {{ include('quack/_delete_form.html.twig') }}#}
{% endblock %}